### ISSUE TITLE
Consider adding cn/gpu algorithm

### ISSUE THREAD

**Issue by setuidroot** [todxx/teamredminer#112]
I'm sorry to ask this (especially on here, but I'm not on Discord and I don't know any other way to message you.)  Please don't take this as sounding presumptuous or expectative in any way.  This is a suggestion more than a request (well, a little of both I suppose.)  I ask because I like TRM a lot (it's by far the best CN miner I've used; I get more than an 8.5% hashrate gain on most CN algos even after the 2.5% dev fee.)  

Anyways, my suggestion is that you consider adding the cn/gpu algo to TRM.  Specifically I ask because cn/gpu is one of the available algos to mine on MoneroOcean and it can be quite profitable at times.  I'm not a fan of Ryo, nor am I here to shill coins.  I mine what is most profitable via MO pool and get paid in XMR.  Sometimes cn/gpu is the most profitable algorithm to mine, I was using xmrigMO's algo switching miner (including cn/gpu.)  But I have switched to TRM exclusively with MO's MetaMiner.

I read that xmrig is slower at cn/gpu than stak because (out of respect for stak's devs) xmrig's devs didn't take stak's cn/gpu code enhancements (a respect that, IMHO, was broken when stak devs took all of xmrig's latest RandomX code contributions and released their RandomX GPU code without xmrig's well earned dev fees :thinking:.)  I haven't used stak since aeon-stak-cpu was depreciated :sweat: so I cannot personally attest to stak being better than xmrig at cn/gpu (and I don't want to use stak.)  I also don't want to fan the flames by asking xmrig to take stak's cn/gpu code enhancements :thinking: plus I know a TRM cn/gpu miner would be better than xmrig or stak :wink:

If you don't have the time or whatnot that's cool, I respect that.  I think this would be a good algo for you guys because people could use TRM to mine more CN variants on MO pool.  I use MetaMiner with TRM for cn/r, cn/xhv, cn_saber (tube), trtl_chukwa (turtlecoin), cn/half (MSR), cn-pico/trtl (IRD) and cn/rwz (Graft.)  I'd love to add TRM with cn/gpu to that algo switch list.  IIRC Ryo isn't the only coin that uses cn/gpu algo (but currently it's the only one on MO pool.)  I'm hoping MO might add Conceal (CCX.)  I'd like that since TRM already supports it :grinning:.

Anyways, this is just a friendly request/suggestion.  Please don't take this as a noob demanding functionality or asking the common question cycle: "when? why TRM not do this yet? why fees?" :sweat_smile:  Perhaps you have a good reason why you haven't added cn/gpu; maybe cn/gpu is too small of a market to be bothered with implementing it.  Or maybe you haven't thought about it (that's why I brought this issue up, as a suggestion for you to consider.)  Feel free to close this "issue" after you've read it, this is just my way of communication.

Ah... equilibria (XEQ) is the other cn/gpu coin that I'm aware of (it's on hashvault and herominers among other pools.)

**Comment by SomethingGettingWrong** [comment]
I have been wondering this myself. i use it exclusively however Conceal ALgo an Cn-GPU are the only good FP32 math included algos that are popular. Im not sure if that swhy they havent included it or what. But FPGA's being on the network with Conceal Or CN-gpu wouldnt matter as the diesize electrical usage and pure Floating point performance is what determines profit. Basicly Cn-gpu doesnt try to fight fpga by making it where they cant mine. Instead it embraces it.. and instead floating point math at what ever diesize is the cheapest (hence gpus) is the best choice. so with that being said. Cn-gpu is actually getting more and more higher in the profitable section as older gpu's are phased out on new algos..yet the newer Gpus core count and performance is only more profitable because of diesize shrinkage.  

I would hope one day they add it. as im forced half the time to stop using this miner for ryo when its more profitable. but i love this mienr more thn others.

**Comment by zulicheg** [comment]
Please add the CN-GPU algorithm to mine Ryo.

**Comment by setuidroot** [comment]
#154
