### ISSUE TITLE
will cryptonight/r be supported before the fork?

### ISSUE THREAD

**Issue by caowenyu75** [todxx/teamredminer#26]

**Comment by srwx666** [comment]
3 days to fork, should we search for other software ?

**Comment by todxx** [comment]
Hey guys, sorry for the radio silence lately.   We're hard at work getting cnr ready for the fork.  Currently we expect to have it ready about a day or so before the fork.

That said, it's always possible that unexpected delays come up and we can't release before the fork.  So having a back-up miner ready is probably a good idea.

Due to the random code generation in cnr, it is a huge development effort on our end to get it working since we don't use opencl for our kernels like other miners.

**Comment by Spaceguide** [comment]
hoping for the best, back up miner ready...

**Comment by caowenyu75** [comment]
thanks for the heads-up

**Comment by todxx** [comment]
Release v0.4.0 posted with CN/R support!

**Comment by MoneroChan** [comment]
and don't forget to change algo to "cnr" tomorrow , because cnv8 still shows as default :)

**Comment by todxx** [comment]
Closing since this algo is now supported.
