### ISSUE TITLE
0.4.1 not run with intel igp in win7

### ISSUE THREAD

**Issue by Quake4** [todxx/teamredminer#32]
![image](https://user-images.githubusercontent.com/29517243/54334554-74e7ba80-4637-11e9-897a-af3fd6eeb384.png)

log isnt created.
0.3.10 works wine

**Comment by Quake4** [comment]
![image](https://user-images.githubusercontent.com/29517243/54334598-8df06b80-4637-11e9-8733-32fa8a956f8c.png)

**Comment by Quake4** [comment]
![image](https://user-images.githubusercontent.com/29517243/54334641-aa8ca380-4637-11e9-8ed3-757a7e8734f5.png)

**Comment by todxx** [comment]
I believe you are hitting a bug we have with older windows terminals when we try to enable console colors.  We thought we fixed this last release, but it turns out there's still a bit more to do.  We should have it fixed in the next release.

For the time being, you can run with --disable_colors and that should get your terminal output working again.

**Comment by Quake4** [comment]
Yes `--disable_colors` help me, but all other miners works fine.

**Comment by Quake4** [comment]
thanks for 4.2
