### ISSUE TITLE
teamred crashing

### ISSUE THREAD

**Issue by Blisk** [todxx/teamredminer#394]
I have in computer RX560 4Gb graphic card and windows 10, updated fully and latest radeon driver.
mining on kawpow
teamred.exe -a kawpow -o stratum+tcp://kawpow.eu.nicehash.com:3385 -u 3AT31EBzjDy2wrQRu6gpQbHsxeFVCg4Amu --enable_compute --temp_limit=90 --temp_resume=80 --log_file=logfile.txt
And I notice it just stop working after a while, than I need to start it again and it works about 1 hour and than stop to work.
Is there a way to solve this?

**Comment by Kerney666** [comment]
Kawpow is a taxing algo. You don't mention your clocks/voltage settings. It sounds like "just" a regular gpu crash, which is typically handled by lowering core and/or mem clk to stress the gpu less. Also, make sure your temps are ok. I see you've changed the default stop/resume temps, it's really not advisable to run a 560 so that it hits 80-90C.

Somewhat related: 0.8.5 will be out in an hour or two and has built-in support for setting clocks so you don't need to use external tool(s).
