### ISSUE TITLE
Tmem is always 0

### ISSUE THREAD

**Issue by cultcode** [todxx/teamredminer#410]
device: AMD 6700XT, AMD 6800XT
driver: 21.8.2

**Comment by Kerney666** [comment]
Unfortunately, AMD does not include the memory temperature sensor in their libraries, it's very unclear why, since they do expose it on linux. You can see that the Radeon Software itself doesn't include the mem temp for RDNA2 gpus. It's available for Vegas and RDNA/Navi10 but not the current generation.

There's only one tool (HWiNFO64) that has managed to hack its own support by (my assumption) doing direct i2c communication with the gpu. You can use it to check their "Memory Junction Temperature" to manually check your mem temp isn't going crazy.
