### ISSUE TITLE
API: Hashrate on faulty GPU reported incorrectly

### ISSUE THREAD

**Issue by orvych** [todxx/teamredminer#55]
I use my-own monitoring tool that utilizes TRMiner API. In this example, one GPU failed, average values reported by (30s) dropped to zero while instant values are not:

GPU0 Hash:514H/s Avg:512H/s...
GPU1 Hash:**503**H/s Avg:**0**H/s...

Expected behavior: on faulty GPU all instant H/s values should drop to zero.
Let me know if you need more details.

Thanks.

**Comment by todxx** [comment]
Sorry for the late reply.  After looking at the code we only provide two hashrate valuee: the average since the miner has started, and the hashrate over the last log interval (by default 30 seconds).  There is no instantaneous hashrate provided, so I think you might be interpreting the data incorrectly.
