### ISSUE TITLE
0.9.4.7 5700 XT Mem Temp Between 68° - 88°C R-Mode

### ISSUE THREAD

**Issue by acmesoft-arg** [todxx/teamredminer#599]
I have a RX5700 XT (ASRock). With B Mode it works at 78°-80° depends of the day. But with the new R Mode: memory temperature fluctuates between 68 and 88°. I guess that's not expected behavior.
The RX5600XT GPUs do not have the same fluctuating behaviour, but instead remain stable. Do you think this board is part of the 1% that is estimated not to work?

OS: Hive, Mining Eth Only
Core: 1075 CV: 670 MCV: 735 MClock: 930 MemVolt: 1350

Thank You.

**Comment by blackmennewstyle** [comment]
This is mostly why they created the R-Mode, to allow you to lower your core/memory voltage and lower your temperatures in the process :)

**Comment by acmesoft-arg** [comment]
Sorry but I don't understand, do you mean undervolt mem to stabilize the temps?
88° is 10° more than the original status of the GPU. There are cold days here, in summer I think will be more than 90° is risky.

**Comment by pdieppa** [comment]
- 5700XT/5700: big winner. Core clk 1050-1075 MHz is now enough to
  sustain 56 MH/s. Can almost always run at sub-700mV core voltage.
  
- 5600XT: big winner. Core clk 950 MHz supports 42 MH/s, core voltage
  can be dropped low.

**Comment by CamJava007** [comment]
@pdieppa ...  If you can get the same results with a lower clock.... then it definitely makes sense that the card would work "harder" without lowering the clocks.
Also.... yeah... summer 🥵🥵🥵😂😂😂

**Comment by blackmennewstyle** [comment]
> Ok, thank you all. I will try undervolt more the gpu. But i Think is near of the limit.

Sorry if i confused you, it was not my intention. If i may share my experience, i have been minning my RX 5600 XT, RX 5700, RX 5700 XT since two years.
90°C is still fine and normal if your cards are bios-modded with the memory strap overclock.
I will suggest to change the thermal pads if possible at least every 6 months or soon as you notice temperature degradation on your VRAM chips.
Also, heat is always managable, invest in hardware in order to exhaust hot air as fast as possible from your mining location. I'm living myself in Thailand, it's summer all year long here with peaks up to 40 degrees celcius (outside temperature).
There is so much you can do without thinking about buying new GPUs in order to solve an issue, which will be always there if you don't tackle it right now in first place with the right decision.
