### ISSUE TITLE
cnr/avg/pool

### ISSUE THREAD

**Issue by 30240** [todxx/teamredminer#66]
Hi,
thanks a lot for teamredminer!!
I have just a question:
when I press s, it shows this:

GPU 0 [74C, fan 48%] cnr: 1.705kh/s, avg 1.761kh/s, pool 1.255kh/s a:28 r:0 hw:0

What is the meaning of the pool-number?

My card has 1705 kh/s, but the pool only receives 1255kh/s ?

Or what does this mean?

greetings

Eni

**Comment by todxx** [comment]
The pool hashrate is calculated based on the shares submitted and their difficulty.  This is how pools calculate a miner's hashrate.  Our miner implements the same logic that a pool would and prints this pool hashrate value.

This value can vary significantly from your actual hashrate because it is based on submitted shares and finding shares is a random process.  So you could end up finding more or less than the average number expect (which would match the avg hashrate - dev fee).   As the number of shares submitted increases, the variation between pool hashrate and avg hashrate should go down.

There are some things that could lower your pool hashrate compared to your average such as hw-errors and rejects.  If you are seeing hw-errors, these are potentially shares that would have been valid but were not due to a memory or compute error.  Rejects are typically valid shares that were rejected by the pool for some other reason, such as being for a job that expired.

**Comment by 30240** [comment]
Hey todxx,
thank you for the detailed clarification!
Eni
